"""empty message

Revision ID: a537d51563c7
Revises: a12a46fd3c57
Create Date: 2017-03-29 04:47:13.035467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a537d51563c7'
down_revision = 'a12a46fd3c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('data_cadastro', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'data_cadastro')
    # ### end Alembic commands ###
