"""empty message

Revision ID: cb0f8069d230
Revises: a537d51563c7
Create Date: 2017-03-30 19:17:49.867154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb0f8069d230'
down_revision = 'a537d51563c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('is_confidential', sa.Boolean(), nullable=True))
    op.add_column('cliente', sa.Column('senha_hash', sa.String(length=129), nullable=False))
    op.alter_column('cliente', 'data_cadastro',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('cliente', 'email',
               existing_type=mysql.VARCHAR(length=225),
               nullable=False)
    op.alter_column('cliente', 'nome',
               existing_type=mysql.VARCHAR(length=225),
               nullable=False)
    op.alter_column('cliente', 'telefone',
               existing_type=mysql.VARCHAR(length=24),
               nullable=False)
    op.create_unique_constraint(None, 'cliente', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cliente', type_='unique')
    op.alter_column('cliente', 'telefone',
               existing_type=mysql.VARCHAR(length=24),
               nullable=True)
    op.alter_column('cliente', 'nome',
               existing_type=mysql.VARCHAR(length=225),
               nullable=True)
    op.alter_column('cliente', 'email',
               existing_type=mysql.VARCHAR(length=225),
               nullable=True)
    op.alter_column('cliente', 'data_cadastro',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('cliente', 'senha_hash')
    op.drop_column('cliente', 'is_confidential')
    # ### end Alembic commands ###
